apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
  namespace: expensy
type: Opaque
stringData:
  api_url: http://backend:8706
  database_uri: mongodb://admin:supersecret123@mongo:27017/expensy?authSource=admin
  mongo_pass: supersecret123
  mongo_user: admin
  next_public_api_url: http://20.82.53.32.nip.io
  redis_password: myredispassword
  grafana_user: admin
  grafana_password: admin123
  grafana_url:  http://20.82.53.32.nip.io/grafana

  