apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress-api
  namespace: expensy
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"    # ← add this
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"  # ← add this
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8706
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress-tools
  namespace: expensy
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2       # strips prefix for grafana/prometheus
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /metrics(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prometheus
                port:
                  number: 9090

          - path: /grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress-frontend
  namespace: expensy
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1       # pass through as-is
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80